# Generated by Django 5.2.16 on 2026-08-04 09:40

import django.core.validators
import django.db.models.deletion
import newspapers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('name', models.CharField(max_length=100, verbose_name='Bo‘lim nomi')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Bo‘lim',
                'verbose_name_plural': 'Bo‘limlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('name', models.CharField(max_length=150, verbose_name='Gazeta nomi')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='newspapers/logos/', verbose_name='Logotip')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Gazeta',
                'verbose_name_plural': 'Gazetalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('issue_number', models.PositiveIntegerField(verbose_name='Nashr soni')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('publication_date', models.DateField(verbose_name='Nashr sanasi')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('nfc_slug', models.SlugField(max_length=180, unique=True, verbose_name='NFC identifikatori')),
                ('description', models.TextField(blank=True, verbose_name='Qisqacha mazmun')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=newspapers.models.issue_cover_upload_path, verbose_name='Muqova rasmi')),
                ('original_pdf', models.FileField(blank=True, null=True, upload_to=newspapers.models.issue_pdf_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Original PDF')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='Betlar soni')),
                ('estimated_audio_duration', models.PositiveIntegerField(default=0, help_text='Soniyalarda', verbose_name='Taxminiy audio davomiyligi')),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('PROCESSING', 'Qayta ishlanmoqda'), ('REVIEW', 'Tekshiruvda'), ('PUBLISHED', 'Nashr qilindi'), ('FAILED', 'Xatolik'), ('ARCHIVED', 'Arxivlandi')], default='DRAFT', max_length=20, verbose_name='Holat')),
                ('is_public', models.BooleanField(default=False, verbose_name='Ommaga ochiq')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Nashr qilingan vaqt')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_issues', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan administrator')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issues', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan administrator')),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='newspapers.newspaper', verbose_name='Gazeta')),
            ],
            options={
                'verbose_name': 'Gazeta soni',
                'verbose_name_plural': 'Gazeta sonlari',
                'ordering': ['-publication_date', '-issue_number'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('page_number', models.PositiveIntegerField(verbose_name='Bet raqami')),
                ('page_image', models.ImageField(blank=True, null=True, upload_to=newspapers.models.page_image_upload_path, verbose_name='Bet rasmi')),
                ('raw_text', models.TextField(blank=True, verbose_name='Ajratib olingan matn')),
                ('ocr_text', models.TextField(blank=True, verbose_name='OCR matni')),
                ('final_text', models.TextField(blank=True, verbose_name='Yakuniy matn')),
                ('audio', models.FileField(blank=True, null=True, upload_to=newspapers.models.page_audio_upload_path, verbose_name='Audio')),
                ('processing_status', models.CharField(choices=[('PENDING', 'Navbatda'), ('PROCESSING', 'Qayta ishlanmoqda'), ('READY', 'Tayyor'), ('REVIEW', 'Tekshiruv kerak'), ('APPROVED', 'Tasdiqlandi'), ('FAILED', 'Xatolik')], default='PENDING', max_length=20, verbose_name='Qayta ishlash holati')),
                ('extraction_confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Aniqlik foizi')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='newspapers.issue', verbose_name='Gazeta soni')),
            ],
            options={
                'verbose_name': 'Gazeta beti',
                'verbose_name_plural': 'Gazeta betlari',
                'ordering': ['issue', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=320, verbose_name='URL identifikatori')),
                ('summary', models.TextField(blank=True, verbose_name='Qisqacha mazmun')),
                ('content', models.TextField(verbose_name='Maqola matni')),
                ('author', models.CharField(blank=True, max_length=160, verbose_name='Muallif')),
                ('image', models.ImageField(blank=True, null=True, upload_to=newspapers.models.article_image_upload_path, verbose_name='Asosiy rasm')),
                ('audio', models.FileField(blank=True, null=True, upload_to='newspapers/articles/audio/', verbose_name='Audio')),
                ('reading_order', models.PositiveIntegerField(default=0, verbose_name='O‘qilish tartibi')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy maqola')),
                ('is_published', models.BooleanField(default=False, verbose_name='Nashr qilingan')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='newspapers.category', verbose_name='Bo‘lim')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='newspapers.issue', verbose_name='Gazeta soni')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='newspapers.page', verbose_name='Asosiy bet')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ['issue', 'reading_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('newspaper', 'year', 'issue_number'), name='unique_newspaper_year_issue_number'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('issue', 'page_number'), name='unique_issue_page_number'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('issue', 'slug'), name='unique_article_slug_per_issue'),
        ),
    ]
