# Generated by Django 5.2.16 on 2026-08-04 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='processing_error',
            field=models.TextField(blank=True, verbose_name='Qayta ishlash xatosi'),
        ),
        migrations.AddField(
            model_name='issue',
            name='processing_progress',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Qayta ishlash foizi'),
        ),
    ]
