# Generated by Django 5.2.16 on 2026-08-05 07:28

import django.db.models.deletion
import newspapers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0002_issue_processing_error_issue_processing_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('block_index', models.PositiveIntegerField(verbose_name='Blok indeksi')),
                ('image', models.ImageField(upload_to=newspapers.models.extracted_image_upload_path, verbose_name='Ajratilgan rasm')),
                ('caption', models.TextField(blank=True, verbose_name='Rasm izohi')),
                ('alt_text', models.CharField(blank=True, max_length=500, verbose_name='Rasm tavsifi')),
                ('x0', models.FloatField(default=0)),
                ('y0', models.FloatField(default=0)),
                ('x1', models.FloatField(default=0)),
                ('y1', models.FloatField(default=0)),
                ('width', models.PositiveIntegerField(default=0, verbose_name='Rasm eni')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='Rasm bo‘yi')),
                ('reading_order', models.PositiveIntegerField(default=0, verbose_name='O‘qilish tartibi')),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Nazorat summasi')),
                ('is_ignored', models.BooleanField(default=False, verbose_name='Ko‘rsatilmasin')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_images', to='newspapers.page', verbose_name='Gazeta beti')),
            ],
            options={
                'verbose_name': 'Bet rasmi',
                'verbose_name_plural': 'Bet rasmlari',
                'ordering': ['page', 'reading_order', 'block_index'],
                'constraints': [models.UniqueConstraint(fields=('page', 'block_index'), name='unique_image_block_per_page')],
            },
        ),
        migrations.CreateModel(
            name='PageTextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('block_index', models.PositiveIntegerField(verbose_name='Blok indeksi')),
                ('block_type', models.CharField(choices=[('TITLE', 'Sarlavha'), ('TEXT', 'Oddiy matn'), ('CAPTION', 'Rasm izohi'), ('SIDEBAR', 'Yon blok'), ('UNKNOWN', 'Aniqlanmagan')], default='UNKNOWN', max_length=20, verbose_name='Blok turi')),
                ('raw_text', models.TextField(verbose_name='Ajratilgan matn')),
                ('final_text', models.TextField(blank=True, verbose_name='Yakuniy matn')),
                ('x0', models.FloatField(default=0)),
                ('y0', models.FloatField(default=0)),
                ('x1', models.FloatField(default=0)),
                ('y1', models.FloatField(default=0)),
                ('font_size', models.FloatField(default=0, verbose_name='Shrift o‘lchami')),
                ('font_name', models.CharField(blank=True, max_length=180, verbose_name='Shrift nomi')),
                ('is_bold', models.BooleanField(default=False, verbose_name='Qalin matn')),
                ('reading_order', models.PositiveIntegerField(default=0, verbose_name='O‘qilish tartibi')),
                ('is_ignored', models.BooleanField(default=False, verbose_name='E’tiborga olinmasin')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_blocks', to='newspapers.page', verbose_name='Gazeta beti')),
            ],
            options={
                'verbose_name': 'Matn bloki',
                'verbose_name_plural': 'Matn bloklari',
                'ordering': ['page', 'reading_order', 'block_index'],
                'constraints': [models.UniqueConstraint(fields=('page', 'block_index'), name='unique_text_block_per_page')],
            },
        ),
    ]
