# Generated by Django 5.2.16 on 2026-08-05 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0003_pageimage_pagetextblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_blocks',
            field=models.ManyToManyField(blank=True, related_name='articles', to='newspapers.pagetextblock', verbose_name='Manba matn bloklari'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='newspapers.pageimage', verbose_name='Manba rasmi'),
        ),
    ]
