# Generated by Django 5.2.16 on 2026-08-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0004_article_source_blocks_article_source_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Nashr qilingan vaqt'),
        ),
    ]
