# Generated by Django 5.2.16 on 2026-08-04 09:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newspapers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfcVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Anonim sessiya')),
                ('device_type', models.CharField(blank=True, max_length=30, verbose_name='Qurilma turi')),
                ('browser', models.CharField(blank=True, max_length=50, verbose_name='Brauzer')),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ochilgan vaqt')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_visits', to='newspapers.issue', verbose_name='Gazeta soni')),
            ],
            options={
                'verbose_name': 'NFC ochilishi',
                'verbose_name_plural': 'NFC ochilishlari',
                'ordering': ['-opened_at'],
            },
        ),
    ]
